version: '3'
services:
  db:
    image: postgres:10
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file:
      - .env
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/comp_code
    ports:
      - "3000:3000"
    links:
      - "db:db"
    depends_on:
      - db
    env_file: .env

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    links:
      - "web:web"
    depends_on:
      - web
